### ISSUE TITLE
System.IO.FileNotFoundException on startup

### ISSUE THREAD

**Issue by Amomum** [rumkit/PixelPixie#15]
I cloned latest master and built it with no problems. However, when started without debugger it says:

> Необработанное исключение: System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "CommandLine, Version=1.9.71.2, Culture=neutral, PublicKeyToken=de6f01bd326f8c32" либо одну из их зависимостей. Не удается найти указанный
 файл.
   в Pixie.Program.Main(String[] args)

**Comment by rumkit** [comment]
checked the latest master commit - all seems to be ok
please check CommandLine library in project references. It should be downloaded at first build via nuget
try to run `nuget restore -SolutionDir .` from solution dir and paste output here
nuget.exe can be downloaded from https://www.nuget.org/downloads

**Comment by Amomum** [comment]
It said:

> MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
> Все пакеты, перечисленные в packages.config, уже установлены.

**Comment by Amomum** [comment]
Weirdly enough, after I did that, everything started to work. Even freshly cloned and build solution.
